AmNasrProject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', include('coreFa.urls'))

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

coreFa/urls.py
from django.urls import path
from .views import *
app_name = 'coreFa'


urlpatterns = [
    path('home', HomeView.as_view(), name='home'),
    path('', HomeView.as_view(), name='home'),
    path('news-and-articles', NewsListView.as_view(), name='article-list-view'),
    path('news-and-articles/<pk>', NewsDetailView.as_view(), name='article-detail-view'),
    path('galley', GalleryListView.as_view(), name='gallery'),
    path('plans', PlansListView.as_view(), name='plans'),
    path('our-projects', ProjectsView.as_view(), name='our-projects'),
    path('about-haatam-central-baazar', AboutUsView.as_view(), name='about-us'),
    ]

coreFa/models.py
from PIL import Image
from ckeditor_uploader.fields import RichTextUploadingField
from django.db import models

# Create your models here.
from django.db.models.signals import post_save
from django.urls import reverse


class NewsAndArticles(models.Model):
    title = models.CharField('عنوان', max_length=200)
    body = RichTextUploadingField('بدنه خبر و مقاله', null=True, blank=True)
    short_description = models.CharField('توضیح کوتاه',
                                                 default='توضیح کوتاه اتوماتیک', max_length=200)
    pic = models.ImageField(upload_to='NewsAndArticles', null=True, blank=True)
    created_at = models.DateTimeField('تاریخ ایجاد',auto_now_add=True)
    active = models.BooleanField('فعال', default=True)
    author = models.CharField('نویسنده',max_length=200, default='امیر نصرالله')
    slug = models.SlugField('اسلاگ', max_length=150, allow_unicode=True, blank=True, null=True)

    class Meta:
        verbose_name_plural = 'اخبار و مقالات'
        verbose_name = 'خبر و مقاله'

    def __str__(self):
        return self.title

    def get_article_detail_view(self):
        return reverse('coreFa:article-detail-view', kwargs={
            'pk': self.pk
        })

    # @classmethod
    # def slug_post_create(cls, sender, instance, created, *args, **kwargs):
    #     if created:
    #         instance.slug = instance.title.replace(' ', '-') \
    #                             .replace('.', '-') \
    #                             .replace('(', '-') \
    #                             .replace(')', '-') \
    #                             .replace(':', '-') \
    #                             .replace(',', '-') \
    #                             .replace('--', '-') \
    #                             .replace('"', '-') \
    #                             .replace("'", '-') \
    #                             .lower() + f'-{str(instance.id)}'
    #         instance.save()
    #
    # def save(self, *args, **kwargs):
    #     if not self.slug:
    #         self.slug = self.title.replace(' ', '-') \
    #                         .replace('.', '-') \
    #                         .replace('(', '-') \
    #                         .replace(')', '-') \
    #                         .replace(',', '-') \
    #                         .replace(':', '-') \
    #                         .replace('--', '-') \
    #                         .replace('"', '-') \
    #                         .replace("'", '-') \
    #                         .lower() + f'-{str(self.id)}'
    #         self.save()


# post_save.connect(NewsAndArticles.slug_post_create, sender=NewsAndArticles)


class GalleryImages(models.Model):
    title = models.CharField('عنوان', max_length=150, default='عکس گالری')
    image = models.ImageField('عکس', upload_to='gallery_images')
    description = models.CharField('توضیحات', max_length=150, default='توضیحات عکس')

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        super(GalleryImages, self).save(*args, **kwargs)
        img = Image.open(self.image.path)
        if img.width > 1920 or img.height > 1080:
            output_size = (1920, 1080)
            img.thumbnail(output_size)
            img.save(self.image.path)

    class Meta:
        verbose_name_plural = 'عکس های گالری'
        verbose_name = 'عکس گالری'


class Plans(models.Model):
    title = models.CharField('عنوان پلان', max_length=150, default='پلان')
    image = models.ImageField('عکس', upload_to='plans')
    description = models.CharField('توضیحات', max_length=150, default='توضیحات پلان')

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        super(Plans, self).save(*args, **kwargs)
        img = Image.open(self.image.path)
        if img.width > img.height:
            if img.width > 2560 or img.height > 1440:
                output_size = (2560, 1440)
                img.thumbnail(output_size)
                img.save(self.image.path)
            else:
                if img.width > 2560 or img.height > 1440:
                    output_size = (1440,2560)
                    img.thumbnail(output_size)
                    img.save(self.image.path)

    class Meta:
        verbose_name_plural = 'پلان ها'
        verbose_name = 'پلان'

coreFa/views.py
from django.shortcuts import render, get_object_or_404

from django.views import generic

from coreFa.models import *


class HomeView(generic.View):
    def get(self, request):
        news = NewsAndArticles.objects.all().order_by('created_at').filter(active=True)[:4]
        return render(self.request, 'home.html', context={'news': news})


class NewsListView(generic.ListView):
    model = NewsAndArticles
    template_name = 'new-list-view.html'

    def get_queryset(self):
        return NewsAndArticles.objects.all().order_by('created_at')


class ProjectsView(generic.TemplateView):
    template_name = 'our-projects.html'


class NewsDetailView(generic.DetailView):
    model = NewsAndArticles
    template_name = 'news-detail.view.html'
    context_object_name = 'news'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['news_items'] = NewsAndArticles.objects.all().order_by('created_at').filter(active=True)[:4]
        return context

    def get_object(self, queryset=None):
        news = get_object_or_404(NewsAndArticles, pk=self.kwargs['pk'])
        return news


class GalleryListView(generic.ListView):
    model = GalleryImages
    template_name = 'gallery.html'
    paginate_by = 8

    def get_queryset(self):
        return GalleryImages.objects.all().order_by('-pk')


class PlansListView(generic.ListView):
    model = Plans
    template_name = 'plans.html'
    paginate_by = 8

    def get_queryset(self):
        return Plans.objects.all().order_by('-pk')


class AboutUsView(generic.TemplateView):
    template_name = 'about-haatam-bazaar.html'

templates/about-haatam-bazaar.html
{% extends 'base.html' %}
{% load tags %}
{% load jalali_tags %}
{% load thumbnail %}
{% load static %}
{% block content %}
 <section class="page-section-header">
        <a class="me-1 text-black" href="{% url 'coreFa:home' %}"><h3>صفحه نخست</h3></a>
        <div class="d-block text-black pt-3" style="border-top: 2px solid var(--black-color);"><h1>درباره پروژه</h1></div>
    </section>
		<div class="mx-auto py-4 container-c" style="width: 95%;max-width: 1600px">
			<div class="row justify-content-center">
				<div class="col-12 mx-1 mx-md-2 px-2 px-md-5 py-3 bg-white rounded shadow d-flex flex-column justify-content-start align-items-center">
				<h3 class="rtl text-white bg-black shadow-lg my-4 px-1 px-md-4 py-3 rounded-10 w-100 text-center">
					توسعه میدان میوه و تره بار مرکزی استان البرز بازار حاتم
				</h3>
                    <br><br>
				<div class="rtl">

					<h4 class="article-header mx-auto mx-md-0 my-2 rounded-10 text-center mt-3">ساخت و توسعه</h4>
                    <img loading="lazy" class="rounded float-md-start mx-1 me-md-3 article-img" src="{% static 'img/hatam-entrance.webp' %}" alt="بازار مرکزی حاتم">
                    <p class="article-p text-justify">
						<span style=""> {{ 'میدان فعلی تره بار مرکزی کرج در سال 1367 به تصمیم مدیران وقت به منظور ساماندهی عرضه میوه و تره بار در کرج و حومه در زمین متعلق به شهرداری کرج با مشارکت حجره داران فعلی برای جمعیتی در حدود سیصد هزار نفر در قالب 180 حجره طراحی و اجرا شده است. بدین صورت که %25 از اعیانی حجرات احداثی متعلق به شهرداری کرج و %75 اعیانی حجرات متعلق به حجره داران می باشد. با گذشت بیش از دو دهه از راه اندازی پروژه مزبور و افزایش جمعیت کرج و حومه به حداقل ده برابر آن زمان (حدود سه میلیون نفر)، میدان مزبور در حال حاضر پاسخگوی نیاز شهروندان نبوده، به همین دلیل توسعه میدان مزبور و ایجاد میادین موازی همواره مورد تأکید مسئولین استان البرز و کلانشهر کرج بوده است. در همین راستا در سال 1392 بنا بر تقاضا و دعوت استاندار وقت و شهردار کلانشهر کرج عملیات احداث پروژه توسعه میدان در قالب«سامانه فروش محصولات کشاورزی» با خریداری زمین به حدود مساحت 30000 مترمربع در ضلع غرب و جنوب میدان فعلی شروع گردید و در طول بیش از 5 سال پیگیری مداوم و اخذ مجوزهای قانونی پروژه از مراجع ذیصلاح من جمله اداره کل جهاد کشاورزی، محیط زیست، راه و شهرسازی، سازمان صمت استان، اداره کل امور زیربنایی استانداری و در نهایت شورای برنامه ریزی استان اخذ و با صدور پروانه توسط شهرداری کرج عملیات ساختمانی آن در سال 1397 شروع گردید.'|persian_int_not_cs }}</span>
                        <br>
                        					<h4 class="article-header mx-auto mx-md-0 my-2 rounded-10 text-center mt-3">طرح و سازه</h4>
                    <p class="article-p" style="padding-bottom: 0">{{ 'با بهره گیری از جدیدترین تکنولوژی و متریال سال 2019 – 2023 بر آن شدیم تا سازه های مستحکم و به روز را به مشتریان ارائه دهیم .'|persian_int_not_cs }}
                    <br>
                        <a class="text-info" target="_blank" href="{% url 'coreFa:plans' %}">>> مشاهده پلان ها</a>
                        <br>
                        <a class="text-info" target="_blank" href="{% url 'coreFa:gallery' %}">>> مشاهده عکس های پروژه</a>
                    </p>


					<h4 class="article-header mx-auto mx-md-0 my-2 rounded-10 text-center mt-3">پارکینگ</h4>
                    <p class="article-p" style="padding-bottom: 0">{{ 'به دلیل کمبود پارکینگ خودرو و ازدحام جمعیت در میدان تره بار و حومه آن ، مدیران پروژه تصمیم به ساخت پارکینگ های متعدد جهت رفع موانع ترافیکی و اطمینان خاطر حجره داران و مشتریان عزیز گرفته و ماحصل آن 500عدد پارکینگ در 3 طبقه گردید.'|persian_int_not_cs }}
                        <br>
                        <a class="text-info" target="_blank" href="{% url 'coreFa:plans' %}">>> مشاهده پلان ها</a>
                    </p>

					<h4 class="article-header mx-auto mx-md-0 my-2 rounded-10 text-center mt-3">دسترسی و تجهیزات سردخانه ای</h4>
                    <p class="article-p" style="padding-bottom: 0">{{ 'در دنیای امروز که مهم ترین اصل روزمرگی دسترسی آسان به هر محصول مورد نیاز می باشد و از آنجاییکه مرکبات و سبزیجات نیاز روزانه هر فرد می باشد و مرکبات بسته به نوع، فصلی می باشد با احداث سردخانه برای مجموعه سهولت در دسترسی به انواع سبزیجات را فراهم نموده است.'|persian_int_not_cs }}
					</p>

					<h4 class="article-header mx-auto mx-md-0 my-2 rounded-10 text-center mt-3">شعبه بانکی</h4>
                    <p class="article-p" style="padding-bottom: 0">{{ 'در مجموعه بازار حاتم سامانه فروش مستقیم محصولات کشاورزی به جهت سهولت در انجام امور بانکی ، یک شعبه به بانک اختصاص داده شد تا امور بانکی و پولی مجموعه را انجام دهد.'|persian_int_not_cs }}
					</p>


					<h4 class="article-header mx-auto mx-md-0 my-2 rounded-10 text-center mt-3">امکانات دیگر</h4>
                    <p class="article-p" style="padding-bottom: 0">{{ 'از دیگر امکانات رفاهی مجموعه می توان به فروشگاه ، چایخانه ، فضای سبز و .... نام برد.'|persian_int_not_cs }}
					</p>

                    <br><br>
					<h4 class="article-header bg-info mx-auto mx-md-0 my-2 rounded-10 text-center mt-3 text-justify">بهداشت و فاضلاب و پسماند</h4>
                    <img loading="lazy" class="rounded float-md-start mx-1 me-md-3 article-img" src="{% static 'img/septic-system.webp' %}" alt="سیستم فاضلاب بازار مرکزی حاتم" width="40%" height="450px">
                    <p class="article-p" style="padding-bottom: 0">{{ 'یکی دیگر از شاخصه های بارز فنی و بهداشتی این مجموعه که در سطح کشور در نوع خود بدیع و بی مانند است ، سیستم دفع پسماند سپیتیک SEPTIC  می باشد ، علت بهره گیری  از این سیستم دفع پسماند از یک سو حساسیت در حفظ بهداشت و کیفیت توزیع میوه و تره بار و از سویی دیگر ضرورت حفظ محیط زیست می باشد .'|persian_int_not_cs }}
                    </p>
                    <h5 class="article-header bg-info mx-auto mx-md-0 my-2 rounded-10 text-center mt-3">سیستم سپتیک</h5>
                    <p class="article-p text-justify" style="padding-bottom: 0">{{'سیستم‌های سپتیک تانک نوعی تأسیسات فاضلاب در محل OSSF هستند . مخازن سپتیک امکان دفع ایمن فاضلاب را فراهم می کند. سپتیک تانک ها معمولاً به صورت مدفون و در فاصله 50 متری از محل نصب می شوند. این مخازن معمولاً از دو محفظه یا محفظه و یک مخزن تشکیل شده اند که فاضلاب را از یک لوله ورودی دریافت می کند.'|persian_int_not_cs }}
					</p>
                    <p class="article-p" style="padding-bottom: 0">{{'انواع مختلف تصفیه فاضلاب غیرمتمرکز، اگر به درستی اجرا شوند، می توانند از سلامت عمومی محافظت کنند، منابع ارزشمند آب را حفظ کنند و منافع اقتصادی را برای یک جامعه ایجاد کنند. '|persian_int_not_cs }}
					</p>
                    <h5 class="article-header bg-info mx-auto mx-md-0 my-2 rounded-10 text-center mt-3">مزایای استفاده از سپتیک فاضلاب چیست ؟</h5>
                    <p class="article-p" style="padding-bottom: 0">
                        <span class="fw-bold">مزایای سلامت عمومی: </span>
                        {{'استفاده صحیح از سیستم های تصفیه غیرمتمرکز خطر انتقال بیماری و قرار گرفتن انسان در معرض عوامل بیماری زا را که می تواند از طریق آب آشامیدنی، آب های سطحی و آلودگی بستر صدف ها رخ دهد، کاهش می دهد .'|persian_int_not_cs }}
					</p>
                    <p class="article-p" style="padding-bottom: 0">
                        <span class="fw-bold">مزایای زیست محیطی :</span>
                        {{' تصفیه فاضلاب، آلودگی را از آب های سطحی حذف می کند، سفره های زیرزمینی را تغذیه می کند و باعث افزایش حجم آب های زیرزمینی می گردد.'|persian_int_not_cs }}
					</p>
                    <p class="article-p" style="padding-bottom: 0">
                         <span class="fw-bold">مزایای اقتصادی :</span>
                        {{' سیستم های فاضلاب غیرمتمرکز به جوامع در کاهش هزینه های زیرساختی و مصرف انرژی در ساخت تصفیه خانه های متمرکز و سیستم های جمع آوری فاضلاب شهری کمک می کند .'|persian_int_not_cs }}
					</p>


				</div>
				</div>
			</div>
		</div>

{% endblock %}

templates/footer2.html
{% load static %}
{% load tags %}
<footer class="d-flex flex-column">
	<div class="footer" id="footer">
		<div class="col-12 py-2 py-md-2" style="border-bottom: 1px solid rgba(0,0,0,0.8);">
		<div class="container-fluid mx-auto d-flex flex-column flex-xl-row justify-content-between align-items-start align-content-md-center rtl">
			<div class="d-flex flex-column footer-row-one-item">
				<span class="text-dark">با
					ما
					همراه باشید
				</span>
				<div class="d-flex align-items-center mt-3 w-100">
					<div class="footer-social w-100">
						<div class="social d-flex">
							<a rel="noreferrer" class="facebook" href="https://www.linkedin.com/in/%D8%A8%D8%A7%D8%B1%D8%A7%D9%86-%D8%B3%D8%A7%D8%B2%D9%87-653549259/" target="_blank"><i class="fab fa-linkedin"></i></a>
							<a rel="noreferrer" class="whatsapp" href="https://t.me/Amirnasrolah" target="_blank"><i class="fab fa-whatsapp"></i></a>
							<a rel="noreferrer" class="instagram" href="https://www.instagram.com/bco_construct/?hl=en" target="_blank"><i class="fab fa-instagram"></i></a>
							<a rel="noreferrer" class="telegram" href="https://t.me/Amirnasrolah" target="_blank"><i class="fab fa-telegram-plane"></i></a>
						</div>
					</div>
				</div>
			</div>
			<div class="d-flex flex-column footer-row-one-item">
				<span class="text-dark">
					<i class="fa fa-phone-alt py-1 px-2 text-white bg-black ms-1" style="border-radius: 4px"></i>
					{{ '09120407821'|persian_int_not_cs }}
					<span class="me-2 text-shadow-dark">آقای نصرالله </span>
				</span>
				<span class="text-dark rtl mt-1">
					<i class="fa fa-envelope text-white px-2 py-1 bg-black ms-1" style="border-radius: 4px"></i>
					<span class="text-dark">amirn059@gmail.com</span>
				</span>
				<span class="mt-2 text-dark">{{'همه روزه از 8 صبح تا 8 شب آماده پاسخگویی هستیم'|persian_int_not_cs  }} </span>
			</div>
			<div class="d-flex flex-column footer-row-one-item">
				<div class="footer-item">
					<div>
						<div class="rtl text-justify footer-text pt-3">
							<i class="fa fa-map-marker ms-2 text-black" aria-hidden="true"></i>
							<span class="text-black text-shadow-dark"> دفتر مرکزی : </span>
							<span class="text-shadow-dark"> {{ 'خیابان خالد اسلامبولی، خیابان 16 پلاک 2، طبقه 4 واحد 8'|persian_int_not_cs  }}
                            </span>
						</div>
					</div>
				</div>
			</div>
    	</div>
	</div>
		<div class="footer-holder container-fluid">
			<div class="footer-item">
				<div class="footer-header section-header" style="height: 40px">
					<span class="about-span">بازار مرکزی حاتم</span>
{#					<span class="about-span me-4 text-light-color" style="font-size: 13px">بازار مرکزی حاتم</span>#}
				</div>
				<div>
					<div class="rtl footer-text pt-3 text-shadow-dark">

						<span> {{ 'میدان فعلی تره بار مرکزی کرج در سال 1367 به منظور ساماندهی عرضه میوه و تره بار در کرج و حومه در زمین متعلق به شهرداری کرج با مشارکت حجره داران فعلی برای جمعیتی در حدود سیصد هزار نفر در قالب 180 حجره طراحی و اجرا شده است. بدین صورت که 25 درصد از اعیانی حجرات احداثی متعلق به شهرداری کرج و 75 درصد اعیانی حجرات متعلق به حجره داران می باشد.'|persian_int_not_cs }}</span>
                        <br>
						<span> {{ 'با گذشت بیش از دو دهه از راه اندازی پروژه مزبور و افزایش جمعیت کرج و حومه حداقل ده برابر آن زمان حدود سه میلیون نفر، میدان مزبور در حال حاضر پاسخگوی نیاز شهروندان نبوده، به همین دلیل توسعه میدان مزبور و ایجاد میادین موازی همواره مورد تأکید مسئولین استان البرز و کلانشهر کرج بوده است. '|persian_int_not_cs }}</span>
                        <br>
                        <span class="fw-bold" style="cursor: pointer" id="showText">نمایش ادامه..</span>
						<span id="hiddenText" style="display: none">  {{ 'در همین راستا در سال 1392 بنا بر تقاضا و دعوت استاندار وقت و شهردار کلانشهر کرج عملیات احداث پروژه توسعه میدان در قالب«سامانه فروش محصولات کشاورزی» با خریداری زمین به مساحت 23000 مترمربع در ضلع غرب و جنوب میدان فعلی شروع گردید و در طول بیش از 5 سال پیگیری مداوم، مجوزهای قانونی پروژه از مراجع ذیصلاح منجمله اداره کل جهاد کشاورزی، محیط زیست، راه و. شهرسازی، سازمان صمت استان، اداره کل امور زیربنایی استانداری و در نهایت شورای برنامه ریزی استان اخذ و با صدور پروانه توسط شهرداری کرج عملیات ساختمانی آن در سال 1397 شروع گردید.'|persian_int_not_cs }}</span>

					</div>
				</div>
			</div>

			<div class="footer-item">
				<div class="footer-header section-header">
					<span class="about-span">لینک ها</span>
				</div>
				<div class="d-flex flex-column">
					<a class="mb-1 mt-3 pe-3 text-small footer-link" href="{% url 'coreFa:home' %}">
						<i class="fa fa-chevron-left text-black" style="transform: scale(0.8)"></i>
						<span class="text-dark footer-link">صفحه نخست</span>
					</a>

					<a class="my-1 pe-3 text-small footer-link" href="{% url 'coreFa:gallery' %}">
						<i class="fa fa-chevron-left text-black" style="transform: scale(0.8)"></i>
						<span class="text-dark">گالری</span>
					</a>
                    <a class="my-1  pe-3 text-small footer-link" href="{% url 'coreFa:plans' %}">
                        <i class="fa fa-chevron-left text-black" style="transform: scale(0.8)"></i>
                        <span class="text-dark">پلان ها</span>
                    </a>
                    <a class="my-1  pe-3 text-small footer-link" href="{% url 'coreFa:our-projects' %}">
                        <i class="fa fa-chevron-left text-black" style="transform: scale(0.8)"></i>
                        <span class="text-dark">پروژه های دیگر ما</span>
                    </a>

                    <a class="my-1  pe-3 text-small footer-link" href="{% url 'coreFa:article-list-view' %}">
                        <i class="fa fa-chevron-left text-black" style="transform: scale(0.8)"></i>
                        <span class="text-dark">اخبار و مقالات</span>
                    </a>
				</div>
			</div>

			<div class="footer-item d-flex flex-column align-items-center">
				<img class="img-fluid" src="{% static 'img/BCO.webp' %}" alt="باران کانستراکشن لوگو" style='filter: drop-shadow(0px 0px 44px #000); max-width: 250px'>
                <h5 class="mt-4">Powered by BCO</h5>

			</div>
		</div>
		<!--design section-->
		<div class="" style="border-top: 1px solid rgba(0,0,0,0.8)">
			 <div class="rtl container py-3">
				<div class="footer-design">
					<span class="d-flex justify-content-xl-start justify-content-lg-start justify-content-center w-100 mb-xl-0 mb-2 text-dark">
						 ©2021 طراحی و پیاده سازی :
						فرهود وطن زاده
					</span>
					<div class="d-flex justify-content-xl-end justify-content-lg-end justify-content-center align-items-center w-100">
						<a rel="noreferrer" href="https://t.me/Farhoodva" target="_blank"><i class="fab fa-telegram-plane mx-3"></i></a>
						<a rel="noreferrer" href="https://www.instagram.com/farhoodva/" target="_blank"><i class="fab fa-instagram mx-3"></i></a>
					</div>
				</div>
			 </div>
		</div>
	</div>
</footer>
{% include 'scripts.html' %}

templates/navbar.html
{% load tags %}
{% load static %}

        <!-- Nav Bar Start -->
        <div class="navbar navbar-expand-lg bg-black navbar-dark">
            <div class="container-c">
                <a class="navbar-brand" href="{% url 'coreFa:home' %}">
                    <img src="{% static 'img/hatam.webp' %}" alt="لوگوی بازار حاتم">
				</a>
				<button id="navbar-toggler-icon" type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
                    <span class="navbar-toggler-icon bg-black text-black"></span>
                </button>
                <div class="collapse navbar-collapse justify-content-between py-2" id="navbarCollapse">
                    <div class="navbar-nav ms-auto rtl">
                        <a href="{% url 'coreFa:home' %}" class="nav-item nav-link">صفحه نخست</a>

                        <a  class="nav-item nav-link" href="{% url 'coreFa:gallery' %}">گالری</a>
                        <a  class="nav-item nav-link" href="{% url 'coreFa:plans' %}">پلان ها</a>
                        <a  class="nav-item nav-link" href="{% url 'coreFa:our-projects' %}">پروژه های دیگر ما</a>
                        <a  class="nav-item nav-link" href="{% url 'coreFa:article-list-view' %}">اخبار</a>
                        <a href="{% url 'coreFa:about-us' %}" class="nav-item nav-link sm-hide">درباره پروژه</a>

{#                        <div class="btn-group">#}
{#                          <button type="button" class="nav-link dropdown-toggle" data-bs-toggle="dropdown" data-bs-display="static" aria-expanded="false">#}
{#                            Lingua#}
{#                          </button>#}
{#                          <ul class="dropdown-menu dropdown-menu-lg dropdown_menu-down-out">#}
{#                            <li><a href="{% url 'coreEn:home' %}" class="dropdown-item dropdown-hover" type="button">English</a></li>#}
{#                          </ul>#}
{#                        </div>#}
{#                        <img    data-bs-toggle="tooltip" data-bs-placement="bottom"#}
{#                            data-bs-custom-class="custom-tooltip"#}
{#                            data-bs-title="تم شب"#}
{#                            id="themeLight" class="width-35"#}
{#                            src="{% static 'img/dark-sun.svg' %}" alt="theme-switcher-dark" style="cursor: pointer">#}
{#                        <img   data-bs-toggle="tooltip" data-bs-placement="bottom"#}
{#                            data-bs-title="تم روز"#}
{#                            id="themeDark" class="width-35 d-none" src="{% static 'img/sun.svg' %}" alt="theme-switcher-light" style="cursor: pointer">#}
                    </div>
                </div>
            </div>
            <div class="header">
              <div class="progress-container">
                <div class="progress-bar" id="myBar"></div>
              </div>
            </div>
        </div>
        <!-- Nav Bar End -->

        <!-- contact-us modal -->
		<div id="contactModal" class="modal fade" tabindex="-1">
			<div class="modal-dialog modal-dialog-centered">
				<div class="modal-content">
					<div class="modal-body text-center text-small d-flex flex-column align-items-center justify-content-center bg-black">
						<div class="col-12 mb-4">
							<div class="contact-modal d-flex flex-column align-items-center justify-content-center py-2 px-1 mx-auto bg-black">
                                <div class="team-card-info mt-5">
                                    <img class="img" src="{% static 'img/amir-nasr.webp' %}" alt="عکس آقای امیر نصرالله">
                                    <h1 class="text-center my-2">
										<span class="me-2 text-white">آقای نصرالله </span>
									</h1>
									<p class="text-center my-2 w-100">
										<i class="fa fa-phone me-2 text-white fa-2x" style="width: 35px" aria-hidden="true"></i>
										<span class="text-white" style="font-size: 25px">{{ '09120407821'|persian_int_not_cs }}</span>
                                        </br>
									</p>
									<p class="text-center my-2 w-100">
										<i class="fa fa-envelope px-2 py-1 me-2 text-white fa-2x sm-hide" style="width: 35px" aria-hidden="true"></i>
										<span class="text-white" style="font-size: 25px">amirn059@gmail.com</span>
									</p>
								</div>
							</div>
						</div>
					</div>
					<div class="text-center py-3 bg-orange" >
						<button id="modalClose" type="button" class="btn btn-black-c rounded-pill mx-auto" style="box-shadow: rgba(0,0,0,0.3) 0 0 7px 5px!important" data-bs-dismiss='modal'>بستن</button>
					</div>
				</div>
			</div>
        </div>